export const SET_MONEY = 'SET_MONEY'
export const SET_DElIVERY_ADDRESS = 'SET_DElIVERY_ADDRESS'
export const SET_GIFINFO = 'SET_GIFINFO'
export const SET_GIFINFO_LIST = "SET_GIFINFO_LIST"
export const SET_ADDR_LIST = "SET_ADDR_LIST"
